### ISSUE TITLE
Unable to use fetch-mock as ES6 import 

### ISSUE THREAD

**Issue by BadIdeaException** [wheresrhys/fetch-mock#631]
I can't import fetch-mock using NodeJS 17.6.0 and fetch-mock 9.11.0.

The following minimal example 
`index.mjs`:
```
import fetchMock from 'fetch-mock';
```
`package.json`:
```{
  "main": "index.js",
  "dependencies": {
    "fetch-mock": "^9.11.0",
    "node-fetch": "^3.2.3"
  }
}
```
produces 
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /tmp/node_modules/node-fetch/src/index.js from /tmp/node_modules/fetch-mock/cjs/server.js not supported.
Instead change the require of index.js in /tmp/node_modules/fetch-mock/cjs/server.js to a dynamic import() which is available in all CommonJS modules.
```

It seems that it's trying to import the CommonJS version, so as per [the documentation about importing the correct version](http://www.wheresrhys.co.uk/fetch-mock/#usageimporting), I tried replacing the import with the esm version specifically: 
```
import fetchMock from 'fetch-mock/esm/server';
``` 
Now I get:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/tmp/node_modules/fetch-mock/esm/server' imported from /tmp/index.mjs
Did you mean to import fetch-mock/esm/server.js?`
 ```

Okay, sure, let's try that: 
```
import fetchMock from 'fetch-mock/esm/server.js';
```
Still no dice:
```
TypeError: global$1.XMLHttpRequest is not a constructor
```

I found [issue 446](https://github.com/wheresrhys/fetch-mock/issues/446) and [issue 481](https://github.com/wheresrhys/fetch-mock/issues/481) which seemed similar, and tried downgrading to mock-fetch version 8, but I see the same errors.

And now I don't know what more to try. What am I doing wrong here? Would be grateful for a nudge in the right direction.

**Comment by JSRedondo** [comment]
I think with version 2.x of node-fetch you are able to use require.
With version 3.x of node-fetch you are only able to use import (ES modules).

[https://www.npmjs.com/package/node-fetch#installation](https://www.npmjs.com/package/node-fetch#installation)

**Comment by guilhermechiara** [comment]
@BadIdeaException that happens because on server.js fetch-mock is importing node-fetch using require, which on version 3 is not supported anymore.

To fix it, downgrade your node-fetch version to [2.6.7](https://www.npmjs.com/package/node-fetch/v/2.6.7). That will solve the problem temporarily.

Still server.js might need to change the way it's importing to support node-fetch 3+.

**Comment by BadIdeaException** [comment]
Thanks, I'll look into that. I ended up switching to [nock](https://www.npmjs.com/package/nock) instead. I do like the fetch-mock API better, but since node-fetch 3.0.0 introduced breaking changes, and it can't be long now before fetch comes built-in to NodeJS, I'm not too keen on downgrading. 

Hopefully this will get fixed in fetch-mock quickly.

**Comment by drzraf** [comment]
I guess the `import` should not instantiate object depending upon `XMLHttpRequest` but wait for `.sandbox()` to be run since the user could delegate such a call to after the creation of such a global object (eg, after `jsdom` initialization).

**Comment by perry-mitchell** [comment]
Still getting the following error using this in an ESM setup:

```
TypeError: global$1.XMLHttpRequest is not a constructor
```

Since ESM has been available in Node for quite some time now, I think such issues should be treated as a priority. Will try `nock` instead for now.. hopefully this gets fixed soon.

**Comment by cristiantiradob** [comment]
Same problem here. Any solution?

**Comment by Cobertos** [comment]
> @BadIdeaException that happens because on server.js fetch-mock is importing node-fetch using require, which on version 3 is not supported anymore.
> 
> To fix it, downgrade your node-fetch version to [2.6.7](https://www.npmjs.com/package/node-fetch/v/2.6.7). That will solve the problem temporarily.
> 
> Still server.js might need to change the way it's importing to support node-fetch 3+.

This fixed it for me, even though I don't personally use node-fetch in my project directly, I was able to avoid the error by just downgrading with `npm install node-fetch@^2`

**Comment by wheresrhys** [comment]
Try using fetch-mock@10
